# Generated by Django 5.2.3 on 2025-08-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jemaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='berita',
            options={'verbose_name_plural': 'Berita'},
        ),
        migrations.AlterModelOptions(
            name='galeri',
            options={'verbose_name_plural': 'Galeri'},
        ),
        migrations.AlterModelOptions(
            name='struktural',
            options={'ordering': ['urutan'], 'verbose_name_plural': 'Struktural'},
        ),
    ]
